### ISSUE TITLE
'Verify'domains (github settings) to get the badge on our GitHub profile page

### ISSUE THREAD

**Issue by styvo51** [dltxio/dltxio.github.io#41]

**Comment by styvo51** [comment]
https://github.com/organizations/dltxio/settings/domains

**Comment by Mitchell139** [comment]
I don't have the required permissions on github

**Comment by bitcoinbrisbane** [comment]
> I don't have the required permissions on github

Ok, ill sort

**Comment by bitcoinbrisbane** [comment]
https://geeklaunch.net/blog/how-to-verify-domain-name-on-github-with-namecheap/
