### ISSUE TITLE
HTML standardised e-mail signatures for easy copy/paste 

### ISSUE THREAD

**Issue by styvo51** [dltxio/dltxio.github.io#42]
Design pending.
Existing:
Lucas Cullen
DLTx Pty Ltd :: https://www.dltx.io
ABN 24 634 696 978
PGP 0D2934925D219FFA via keys.openpgp.org
----------------------------------------------------------
Steve Milburn
Director
0456 619 631
DLTX Pty Ltd
http://www.dltx.io
ABN 24 634 696 978
ACN 634 696 978
---------------------------------------------------------

**Comment by bitcoinbrisbane** [comment]
Definitely need yours to be HTTPS and lower case x on DLTx

**Comment by styvo51** [comment]
Hi-res brand assets added to repo
