### ISSUE TITLE
Add Open Collective donation badges to website.

### ISSUE THREAD

**Issue by styvo51** [dltxio/dltxio.github.io#43]
In the footer on the front page?

**Comment by Mitchell139** [comment]
As in just a logo like this? 

![opencollectivelogo](https://user-images.githubusercontent.com/50130291/96830721-38b94480-147f-11eb-8baa-f91de2363fda.png)

**Comment by styvo51** [comment]
Actually, i was thinking more of these badges: or perhaps a link to the page?
https://opencollective.com/dltxio 
Apologies for not making that clear
