### ISSUE TITLE
Wording error

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/dltxio.github.io#46]
"This ceremony allows Project Leads to react immediately and provide developers with product or business information without delay. is used to develop native iOS and Android apps in parallel, reducing delivery times and minimizing outlay."

![spelling](https://user-images.githubusercontent.com/50130291/96805573-478b0180-1455-11eb-9f8a-ae77f4a02d18.PNG)

**Comment by styvo51** [comment]
https://trello.com/c/IWOgeCm8

**Comment by bitcoinbrisbane** [comment]
Easy fix
