### ISSUE TITLE
Improvements to How page

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/dltxio.github.io#56]
Probably a little more than 30 years given the extra people we have.
![1](https://user-images.githubusercontent.com/50130291/114806970-f1d25900-9de8-11eb-999b-5fa60a8cf28e.PNG)

Exact wording is repeated
![2](https://user-images.githubusercontent.com/50130291/114806974-f39c1c80-9de8-11eb-8f7b-ff30cc671fc5.PNG)

**Comment by styvo51** [comment]
**HOW**
As above
*50-years
*"...AWS and Heroku."

Also,
need to alter the sprint table to reflect new pricing:
Snr Dev "$1,400 x2 = $2,800"
"Full Stack Developer $900 x10 = $9,000"
BA "$1,200 x1.5 = $1,800"
Sub Tl " $13,600"
GST "$1,360"
Total "$14,960"

Also, 
"$750" workshop price (x2) to change to "$2,000"
"$3,000" deposit to change to "$5,000"
