### ISSUE TITLE
Adjust pricing in line with recent update

### ISSUE THREAD

**Issue by styvo51** [dltxio/dltxio.github.io#60]
We have adjusted our day rates (new clients immediately, existing clients from July 1) so we need to adjust the pricing table on the "How" page accordingly:

Software Architect, Smart Contract Developer  $1600
Product Owner, Subject Matter Expert  $1600
Technical Lead, Senior Developer  $1400
Business Analyst  $1200
Full Stack Developer  $1000
Developer  $720
Tester  $600

**Comment by JasminFarhi** [comment]
What would be the effort for each of these resources ? As you can see in the screen shot as an example - Senior Developer - Consultancy, Architecture, Dev Team Lead = effort 2

![image](https://user-images.githubusercontent.com/83386965/119062635-a5e38700-ba1a-11eb-9bf3-a7862a979982.png)

Just so I can calculate the subtotal with GST correctly. Thanks :)
