### ISSUE TITLE
Include O365 booking form on website

### ISSUE THREAD

**Issue by styvo51** [dltxio/dltxio.github.io#69]
See "Embed" and default site at 
https://outlook.office365.com/owa/calendar/DLTxPtyLtd@bitcoinbrisbane.com.au/bookings/

**Comment by bitcoinbrisbane** [comment]
Closing

![Screenshot from 2021-07-10 10-23-56](https://user-images.githubusercontent.com/8411406/125146419-05cbf380-e169-11eb-8262-610621e3c58d.png)
