### ISSUE TITLE
Add round circle DLTx logo to website 

### ISSUE THREAD

**Issue by JasminFarhi** [dltxio/dltxio.github.io#98]
At the top of our website should be our logo
<img width="1194" alt="Screen Shot 2021-10-28 at 1 20 45 pm" src="https://user-images.githubusercontent.com/83386965/139180772-5a36d3a5-a90f-4f97-8208-c65aa7d23fd2.png">
.

**Comment by bitcoinbrisbane** [comment]
Good idea.
